DROP TABLE IF EXISTS orders_pizzas CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS pizzas CASCADE;

CREATE TABLE pizzas (id SERIAL PRIMARY KEY, name VARCHAR(25) NOT NULL UNIQUE, price NUMERIC(5,2) NOT NULL);
CREATE TABLE customers (id SERIAL PRIMARY KEY, name VARCHAR(25) NOT NULL UNIQUE, address VARCHAR(255) NOT NULL);
CREATE TABLE orders (id SERIAL PRIMARY KEY, customer_id INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE);
CREATE TABLE orders_pizzas (order_id INT NOT NULL, pizza_id INT NOT NULL, PRIMARY KEY (order_id, pizza_id), 
FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE, FOREIGN KEY (pizza_id) REFERENCES pizzas (id) ON DELETE CASCADE);
